Created working implementation of week numbers and fixed comments (fixes #523)
aleksanderwozniak/table_calendar pull request #634
Opened 2021-12-10 13:24 UTC by LukasMirbt

2021-12-10 13:44 UTC, LukasMirbt commented
It's worth nothing that the week numbers can be wrong if startingDayOfWeek isn't Monday. This is because the algorithm used follows the ISO 8601 standard which defines weeks as starting with Monday

2021-12-19 18:07 UTC, aleksanderwozniak commented
Nice! I'll check it after holidays.

2022-01-26 12:58 UTC, kranfix commented
Hello, what about this PR? Will it be merged?

2022-02-28 18:18 UTC, aleksanderwozniak requested changes
Finally got some time to review this PR... Thanks for submitting it.

Some points worth noting:
It looks good in default config, but can have issues when one wants to use `weekNumberBuilder` -> week number column will always have the same width as remaining columns:

<img src=https://user-images.githubusercontent.com/22658673/156034021-9d2b5696-c4b6-4080-a618-5a7af64e70b9.png width=300>

While this does fix the overflow, #523 had the advantage of scaling the column's width to its content. It might be a better approach overall (using a Row instead of 8-column Table), just needs that overflow fix.


> It's worth noting that the week numbers can be wrong if startingDayOfWeek isn't Monday. This is because the algorithm used follows the ISO 8601 standard which defines weeks as starting with Monday

That's also an important observation. Since TableCalendar can have weeks starting with any day, the current way week numbers are calculated needs to be adapted to support it.

2022-05-05 08:12 UTC, jebstern commented
@aleksanderwozniak Which "week number" PR is a better candidate? This or https://github.com/aleksanderwozniak/table_calendar/pull/523? I could copy & pasted PR, and further develop it based on your PR feedback.

2022-05-06 08:30 UTC, aleksanderwozniak commented
@jebstern #523 might be a bit better candidate in general, as I liked the Row approach (https://github.com/aleksanderwozniak/table_calendar/pull/634#pullrequestreview-895413823) more. Feel free to continue building on top of it, I'll review it once more after you submit updated code.

2022-05-19 19:47 UTC, jeffmayn commented
And thank you for continuing this PR! :)

2022-07-18 14:12 UTC, Yarikml commented
@aleksanderwozniak , Hello, would you like to merge this? This will be really usefull. Thanks for reply

2022-07-20 18:27 UTC, aleksanderwozniak commented
Closing in favor of #697

2022-07-20 18:27 UTC, closed without merging